server.port=${SERVER_PORT:8083}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.max-lifetime=540000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=15000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

app.identity-platform.api-key=${IDENTITY_PLATFORM_API_KEY:}
app.identity-platform.default-password=${IDENTITY_PLATFORM_DEFAULT_PASSWORD:}

party.grpc.port=${PARTY_GRPC_PORT:9093}
account-core.grpc.host=${ACCOUNT_CORE_GRPC_HOST}
account-core.grpc.port=${ACCOUNT_CORE_GRPC_PORT:9091}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.writer-with-default-pretty-printer=true
